packages:
  - '.'

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

patchedDependencies:
  date-fns-tz@1.3.8: patches/date-fns-tz@1.3.8.patch
  date-fns@2.30.0: patches/date-fns@2.30.0.patch
