CREATE TABLE `entrant` (
	`id` text PRIMARY KEY NOT NULL,
	`student_number` text,
	`candidate_number` text NOT NULL,
	`student_name` text NOT NULL,
	`id_card_number` text NOT NULL,
	`gender` text,
	`campus_name` text,
	`department_code` text,
	`department_name` text,
	`major_code` text,
	`major_name` text,
	`grade_year` text,
	`class_name` text,
	`source_place` text,
	`study_years` integer,
	`study_status` text,
	`birth_date` integer,
	`political_status` text,
	`ethnic_group` text,
	`candidate_type` text,
	`freshman_info_status` integer,
	`has_allergen` integer,
	`clothing_size` text,
	`shoe_size` text,
	`register_term` text,
	`register_status` integer,
	`checkin_status` integer,
	`checkin_date` integer,
	`from_poor_county` integer,
	`subject_type` text,
	`subject_code` text,
	`subject_name` text,
	`middle_school_code` text,
	`middle_school_name` text,
	`outside_province_school` integer,
	`landline_phone` text,
	`mobile_phone` text,
	`phone_contact` text,
	`postal_code` text,
	`mail_recipient` text,
	`mail_address` text,
	`candidate_category` text,
	`graduation_category` text,
	`admission_major` text,
	`admission_province` text,
	`family_phone` text,
	`contact_phone` text,
	`single_parent_family` integer,
	`orphan_status` integer,
	`family_annual_income` real,
	`family_population` integer,
	`martyr_child` integer,
	`west_aid_student` integer,
	`pre_register_status` integer,
	`checkin_plan` text,
	`late_reason` text,
	`cadre_apply_status` integer,
	`dorm_apply_status` integer,
	`hardship_apply_status` integer
);
--> statement-breakpoint
CREATE UNIQUE INDEX `entrant_candidate_number_unique` ON `entrant` (`candidate_number`);--> statement-breakpoint
CREATE UNIQUE INDEX `entrant_id_card_number_unique` ON `entrant` (`id_card_number`);--> statement-breakpoint
CREATE INDEX `entrant_student_number_idx` ON `entrant` (`student_number`);
