import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const entrant = sqliteTable(
	"entrant",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		studentNumber: text("student_number"),
		candidateNumber: text("candidate_number").notNull(),
		studentName: text("student_name").notNull(),
		idCardNumber: text("id_card_number").notNull(),
		gender: text("gender"),
		campusName: text("campus_name"),
		departmentCode: text("department_code"),
		departmentName: text("department_name"),
		majorCode: text("major_code"),
		majorName: text("major_name"),
		gradeYear: text("grade_year"),
		className: text("class_name"),
		sourcePlace: text("source_place"),
		studyYears: integer("study_years"),
		studyStatus: text("study_status"),
		birthDate: integer("birth_date", { mode: "timestamp" }),
		politicalStatus: text("political_status"),
		ethnicGroup: text("ethnic_group"),
		candidateType: text("candidate_type"),
		freshmanInfoStatus: integer("freshman_info_status", { mode: "boolean" }),
		hasAllergen: integer("has_allergen", { mode: "boolean" }),
		clothingSize: text("clothing_size"),
		shoeSize: text("shoe_size"),
		registerTerm: text("register_term"),
		registerStatus: integer("register_status", { mode: "boolean" }),
		checkinStatus: integer("checkin_status", { mode: "boolean" }),
		checkinDate: integer("checkin_date", { mode: "timestamp" }),
		fromPoorCounty: integer("from_poor_county", { mode: "boolean" }),
		subjectType: text("subject_type"),
		subjectCode: text("subject_code"),
		subjectName: text("subject_name"),
		middleSchoolCode: text("middle_school_code"),
		middleSchoolName: text("middle_school_name"),
		outsideProvinceSchool: integer("outside_province_school", { mode: "boolean" }),
		landlinePhone: text("landline_phone"),
		mobilePhone: text("mobile_phone"),
		phoneContact: text("phone_contact"),
		postalCode: text("postal_code"),
		mailRecipient: text("mail_recipient"),
		mailAddress: text("mail_address"),
		candidateCategory: text("candidate_category"),
		graduationCategory: text("graduation_category"),
		admissionMajor: text("admission_major"),
		admissionProvince: text("admission_province"),
		familyPhone: text("family_phone"),
		contactPhone: text("contact_phone"),
		singleParentFamily: integer("single_parent_family", { mode: "boolean" }),
		orphanStatus: integer("orphan_status", { mode: "boolean" }),
		familyAnnualIncome: real("family_annual_income"),
		familyPopulation: integer("family_population"),
		martyrChild: integer("martyr_child", { mode: "boolean" }),
		westAidStudent: integer("west_aid_student", { mode: "boolean" }),
		preRegisterStatus: integer("pre_register_status", { mode: "boolean" }),
		checkinPlan: text("checkin_plan"),
		lateReason: text("late_reason"),
		cadreApplyStatus: integer("cadre_apply_status", { mode: "boolean" }),
		dormApplyStatus: integer("dorm_apply_status", { mode: "boolean" }),
		hardshipApplyStatus: integer("hardship_apply_status", { mode: "boolean" }),
	},
	(table) => [
		uniqueIndex("entrant_candidate_number_unique").on(table.candidateNumber),
		uniqueIndex("entrant_id_card_number_unique").on(table.idCardNumber),
		index("entrant_student_number_idx").on(table.studentNumber),
	],
);

export const entrantFieldRemarks = {
	id: { columnIndex: 1, header: "序号" },
	studentNumber: { columnIndex: 2, header: "学号" },
	candidateNumber: { columnIndex: 3, header: "考生号" },
	studentName: { columnIndex: 4, header: "姓名" },
	idCardNumber: { columnIndex: 6, header: "身份证号" },
	gender: { columnIndex: 7, header: "性别" },
	campusName: { columnIndex: 8, header: "所在校区" },
	departmentCode: { columnIndex: 9, header: "院系代码" },
	departmentName: { columnIndex: 10, header: "院系" },
	majorCode: { columnIndex: 11, header: "专业代码" },
	majorName: { columnIndex: 12, header: "专业" },
	gradeYear: { columnIndex: 13, header: "年级" },
	className: { columnIndex: 14, header: "班级" },
	sourcePlace: { columnIndex: 19, header: "生源地" },
	studyYears: { columnIndex: 20, header: "学制" },
	studyStatus: { columnIndex: 22, header: "就读状况" },
	birthDate: { columnIndex: 26, header: "出生日期" },
	politicalStatus: { columnIndex: 29, header: "政治面貌" },
	ethnicGroup: { columnIndex: 30, header: "民族" },
	candidateType: { columnIndex: 38, header: "考生类型" },
	freshmanInfoStatus: { columnIndex: 39, header: "新生是否已填写信息" },
	hasAllergen: { columnIndex: 40, header: "是否有过敏源" },
	clothingSize: { columnIndex: 42, header: "衣服码数" },
	shoeSize: { columnIndex: 43, header: "鞋码" },
	registerTerm: { columnIndex: 44, header: "注册学期" },
	registerStatus: { columnIndex: 45, header: "是否已注册" },
	checkinStatus: { columnIndex: 47, header: "报到状态" },
	checkinDate: { columnIndex: 48, header: "报到时间" },
	fromPoorCounty: { columnIndex: 57, header: "是否来自贫困县" },
	subjectType: { columnIndex: 58, header: "科类" },
	subjectCode: { columnIndex: 59, header: "科类号" },
	subjectName: { columnIndex: 60, header: "科类名称" },
	middleSchoolCode: { columnIndex: 61, header: "毕业中学号" },
	middleSchoolName: { columnIndex: 62, header: "毕业中学名称" },
	outsideProvinceSchool: { columnIndex: 63, header: "是否外省中学" },
	landlinePhone: { columnIndex: 64, header: "固定电话" },
	mobilePhone: { columnIndex: 65, header: "移动电话" },
	phoneContact: { columnIndex: 66, header: "电话联系人" },
	postalCode: { columnIndex: 67, header: "邮政编码" },
	mailRecipient: { columnIndex: 68, header: "收件人" },
	mailAddress: { columnIndex: 69, header: "邮件地址" },
	candidateCategory: { columnIndex: 71, header: "考生类别名称" },
	graduationCategory: { columnIndex: 73, header: "毕业类别名称" },
	admissionMajor: { columnIndex: 75, header: "录取专业名称" },
	admissionProvince: { columnIndex: 76, header: "录取省份" },
	familyPhone: { columnIndex: 78, header: "家庭电话" },
	contactPhone: { columnIndex: 79, header: "联系电话" },
	singleParentFamily: { columnIndex: 95, header: "是否单亲家庭" },
	orphanStatus: { columnIndex: 96, header: "是否孤儿" },
	familyAnnualIncome: { columnIndex: 97, header: "家庭年均收入" },
	familyPopulation: { columnIndex: 100, header: "人口" },
	martyrChild: { columnIndex: 102, header: "是否革命烈士子女" },
	westAidStudent: { columnIndex: 103, header: "是否西部大开发助学工程学生" },
	preRegisterStatus: { columnIndex: 105, header: "预注册情况" },
	checkinPlan: { columnIndex: 106, header: "报到时间" },
	lateReason: { columnIndex: 107, header: "非准时报到原因" },
	cadreApplyStatus: { columnIndex: 108, header: "是否申请学生干部" },
	dormApplyStatus: { columnIndex: 111, header: "是否申请特殊住宿" },
	hardshipApplyStatus: { columnIndex: 114, header: "是否申请困难家庭" },
} as const satisfies Record<
	keyof typeof entrant.$inferSelect,
	{
		columnIndex: number;
		header: string;
	}
>;
